# Generated by Django 2.2.27 on 2022-05-28 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='Экзамен')),
                ('date_exam', models.DateField(null=True, verbose_name='Дaта экзамена')),
                ('teacher', models.CharField(max_length=256, verbose_name='Имя преподавателя')),
                ('exam_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
    ]
