"""
Django settings for student_proj project.

Generated by 'django-admin startproject' using Django 2.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n15ielb@ig=p)ui7ez1%^0=%ckrddu6cy_gp9f3-uk#=z!pxyx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', # приложение отвечающие за админ панель
    'django.contrib.auth', # авторизация
    'django.contrib.contenttypes', # интерфейс для работы с моделями
    'django.contrib.sessions', # поддержка анонимных сеансов. Позвоволяет хранить и извлекать произвольные данные
    'django.contrib.messages', # отоброжение сообщения для пользователей после обработки формы
    'django.contrib.staticfiles', # сбор статических файлов из приложений
    'crispy_forms', # редоктирование BOOTSTARP форм
    'students', # мое приложение по базе студентов
]

""" Промежуточное програманое обеспечение """
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', # улучшение по безопасности цикла запрос/ответ
    'django.contrib.sessions.middleware.SessionMiddleware', # поддержка анонимных сессий
    'django.middleware.common.CommonMiddleware', # запрет доступа к пользовательским. переписование URL
    'django.middleware.csrf.CsrfViewMiddleware', # защита от CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', # добавляет атрибут user, зарегестрированного пользователя
    'django.contrib.messages.middleware.MessageMiddleware', # поддержка сообщений на основе cookie
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # защита от кликджекинга
]

ROOT_URLCONF = 'student_proj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'student_proj.context_processors.students_proc',
            ],
        },
    },
]

WSGI_APPLICATION = 'student_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

from .db import DATABASES


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

PORTAL_URL = 'http://localhost:8000'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# email settings
# please, set here you smtp server details and your admin email
ADMIN_EMAIL = 'admin@studentsdb.com'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = '19931996am@gmail.com'
EMAIL_HOST_PASSWORD = 'MishkaChernyi853'
EMAIL_PORT = 465
EMAIL_USE_TLS = False

CRISPY_TEMPLATE_PACK = 'bootstrap4'
